version: '3'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgres

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/csskp
    ports:
      - "8000:8000"
    expose:
      - '8000'
    depends_on:
      - db
    command: bash -c "cd ./csskp && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
