version: '3'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/csskp:ro
    ports:
      - "8000:80"
    expose:
      - '8000'
    depends_on:
      - db
    command: bash -c "./wait-for-postgres.sh db && apache2ctl -D FOREGROUND"
